steps:
  # This step validates that the Maven and Java environment is correctly set up for the backend.
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'mvn'
    args: ['--version']
    dir: 'backend'
    id: 'Validate Backend Environment'

  # This step validates that the Flutter environment is correctly set up for the frontend.
  - name: 'gcr.io/psychic-surface-236709/flutter-builder'
    entrypoint: 'flutter'
    args: ['--version']
    dir: 'frontend'
    id: 'Validate Frontend Environment'